### ISSUE TITLE
Write notes on Texas transparency laws

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/govt_transparency#4]

**Comment by fdhidalgo** [comment]
This is a great start.  One question on the Transparency Stars Program: are these indicators (like 5 years of budgets) legally required or suggestions?

**Comment by jennyyu1** [comment]
From what I have read, these are more suggestions. There is a checklist for each sub-category. Each item is a "required element" of the sub-category in order to achieve a star, but the entire program acts more as an incentive program than written law. I will look into legal requirements beyond this star program next!

**Comment by fdhidalgo** [comment]
Great job.
